### ISSUE TITLE
transfer repo to github/satzbeleg

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-database#34]
# TODO
- [ ] tidy code up
- [ ] remove security problems
- [ ] don't transfer, initial upload to new git repo
- [ ] archive this repo
