### ISSUE TITLE
zdlstore seperat: Move to cassandra backend

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-database#46]
### TODO
- [x] Design Cassandra Data Model 
- [x] REST API für CQL coden
- [x] Connect CQL-API with Evidence REST API

**Comment by ulf1** [comment]
basically done
