### ISSUE TITLE
Prepare public status on Github

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-database#52]
### Assessment
- A complete rebase is required because real usernames and passwords were hardcoded at some point.
- The demo examples might be copyright protected

### TODO
- [x] Scan for security leaks
    - [x] Ok: `truffleHog --regex --entropy=True https://github.com/satzbeleg/evidence-database.git` 
    - [x] passed, only obvious toy strings: `gittyleaks -link https://github.com/satzbeleg/evidence-database`
    - [x] passed: `truffleHog --regex --entropy=True --since_commit=95eab4aafb3f188c9da778c71d67bc55734b39b3 https://github.com/satzbeleg/evidence-database.git`
- [x] Delete unnecessary comments and code
- [x] Translate comments/readme to EN
- [x] Replace Demo sentences with CC-BY-* sentence examples
- [ ] Transfer the whole repo to a backup location (incl. issues)
- [ ] Create a new repo with a clean code version as initial upload

**Comment by ulf1** [comment]
done
