### ISSUE TITLE
Remove Auth Service from EV project

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-database#66]
https://github.com/satzbeleg/evidence-database/blob/b46d8a8da1da97e3dd20a088fd19288ce0d95278/dbauth.yml#L5

## Related Issue
- [x] https://github.com/satzbeleg/evidence-restapi/issues/77

## TODO
- [ ] Move code into another repo
- [ ] Delete Code from this repo
