### ISSUE TITLE
[Ulf] Add to each sentence a keyword tag to associate it with a study

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-database#73]
## TODO
- [ ] UI, so that principal investigators (Studienleiter) can curate their set of sentence examples (set of parallel sentence examples)
- [ ] New SQL table to save `(investigator_id UUID, sent_id UUID, keywords json[])`, https://github.com/satzbeleg/evidence-database/tree/main/dbappl/setup
- [ ] Read PUD data in EV database, https://github.com/satzbeleg/multilingual-pud-data
- [ ] SQL table to save mapping between parallel sentence examples `(para_id UUID, lang CHAR, sent_id UUID)` with `UNIQUE(para_id, lang)`

**Comment by ulf1** [comment]
we would need another database model for this idea when using cassandra
